### ISSUE TITLE
Add a cpanfile

### ISSUE THREAD

**Issue by zakame** [Perl-Evozon/PearlBee#31]
Decouple the listing of dependencies in Makefile.PL and put it in a cpanfile instead, to further ease the use of `cpanm --installdeps .` as well as support installation using Carton/Pinto/Stratopan.  This should be as easy to implement via the `mymeta-cpanfile` utility of `Module::CPANfile`:

```
perl Makefile.PL
mymeta-cpanfle --no-configure > cpanfile
````

You can further remove the dependency listing in Makefile.PL entirely and read the from cpanfile via `Module::CPANfile->load("cpanfile")`

**Comment by xsawyerx** [comment]
Available in a cleanups branch in #36.

**Comment by xsawyerx** [comment]
#36 was merged and now a `cpanfile` is available. This ticket can be closed.

**Comment by zakame** [comment]
:+1:
